version: "3.3"

services:
  quickwit:
    image: quickwit/quickwit:${SOFTWARE_VERSION_TAG}
    restart: always
    command: run
    ports:
      - 172.17.0.1:16686:7280
    volumes:
      - ./qwdata:/quickwit/qwdata
